swagger: "2.0"
info:
  version: "0.0.1"
  title: buddizApiCatalog
# during dev, should point to your local machine
# host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    x-swagger-router-controller: index
    get:
      description: list elements to provide to the user based on criteria provided
      operationId: ping
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Pong"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /git/push:
    x-swagger-router-controller: git
    get:
      description: return current version of code base
      operationId: getCurrentVersion
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CodeBaseVersion"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: api endpoint for github to allow branch sync
      operationId: push
      parameters:
        - name: webhookInformation
          in: body
          description: contain Github webhook information
          required: true
          schema:
            $ref: "#/definitions/webhookInformation"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CodeBaseVersion"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /demo:
    x-swagger-router-controller: demo
    get:
      description: list elements to provide to the user based on criteria provided
      operationId: doDemo
      parameters:
        - $ref: "#/parameters/demoparam"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Pong:
    type: string
  SuccessResponse:
    type: object
  ErrorResponse:
    type: object
  CodeBaseVersion:
    type: object
  webhookInformation:
    type: object
# define reusable parameters:
parameters:
    demoparam:
      name: demoparam
      in: query
      description: exemple of param to be provided
      required: false
      type: string